### ISSUE TITLE
Letcher et al. (2024) Role for gene conversion in the evolution of cell-surface antigens of the malaria parasite Plasmodium falciparum

### ISSUE THREAD

**Issue by bricoletc** [malariagen/journal-club#12]
This is a (shameless self-plug for) a paper we just released with @iqbal-lab-org that could be of interest to the MalariaGEN folks :))

* **DOI or URL: https://doi.org/10.1371/journal.pbio.3002507**

Best,
Brice

**Comment by alimanfoo** [comment]
Thanks @bricoletc!

**Comment by alimanfoo** [comment]
https://youtu.be/vubawpY1tTA?si=ZhWWKDcbTyfTo_QY
